[package]
name = "soccer_nft"
version = "1.0.0"
authors = []

[addresses]

soccer_coin="0x0a994161cc81f5e8bb7d690467f269213ca91088fba0f15af7ac89cec7a248cc"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dependencies]
soccer_coin = { local="../soccer_coin" }

#[dependencies]

#soccer_coin = {git = "https://github.com/MicroMoveLabStudio/Mini_Soccer.git", subdir = "move/soccer_coin", rev = "main"}

[dev-dependencies]
